-- AnnotateAI Ltd - Complete Database Schema
-- MVP 2.0 - Supabase PostgreSQL + RLS

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- USERS TABLE (synced from Clerk)
-- =====================================================
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  clerk_id TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('client', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast Clerk ID lookups
CREATE INDEX idx_users_clerk_id ON users(clerk_id);

-- =====================================================
-- TASKS TABLE
-- =====================================================
CREATE TABLE tasks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_type TEXT NOT NULL, -- 'text', 'image', 'audio'
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  
  -- Pricing fields
  price_per_unit DECIMAL(10,2) NOT NULL,
  total_units INTEGER NOT NULL,
  total_price DECIMAL(10,2) NOT NULL,
  pricing_reasoning TEXT NOT NULL,
  
  -- Feature flags
  instant_annotation_enabled BOOLEAN NOT NULL DEFAULT true,
  
  -- Metrics
  auto_approved_count INTEGER NOT NULL DEFAULT 0,
  manual_review_count INTEGER NOT NULL DEFAULT 0,
  processing_time_ms INTEGER,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_tasks_user_id ON tasks(user_id);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_created_at ON tasks(created_at DESC);

-- =====================================================
-- ANNOTATIONS TABLE
-- =====================================================
CREATE TABLE annotations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  
  -- Annotation data
  annotation_data JSONB NOT NULL,
  confidence_score DECIMAL(5,4) NOT NULL CHECK (confidence_score >= 0 AND confidence_score <= 1),
  
  -- AI decision tracking
  decision_type TEXT NOT NULL CHECK (decision_type IN ('auto_approved', 'ai_assisted', 'manual_review')),
  ai_provider TEXT CHECK (ai_provider IN ('openai', 'anthropic', 'hybrid')),
  ai_validated BOOLEAN NOT NULL DEFAULT false,
  
  -- Performance metrics
  execution_time_ms INTEGER NOT NULL,
  
  -- Status
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'completed')),
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_annotations_task_id ON annotations(task_id);
CREATE INDEX idx_annotations_decision_type ON annotations(decision_type);
CREATE INDEX idx_annotations_confidence ON annotations(confidence_score DESC);

-- =====================================================
-- PAYMENTS TABLE
-- =====================================================
CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Stripe data
  stripe_payment_intent_id TEXT UNIQUE NOT NULL,
  stripe_checkout_session_id TEXT,
  
  -- Payment details
  amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
  currency TEXT NOT NULL DEFAULT 'gbp',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
  
  -- Metadata
  payment_method TEXT,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_payments_task_id ON payments(task_id);
CREATE INDEX idx_payments_user_id ON payments(user_id);
CREATE INDEX idx_payments_stripe_id ON payments(stripe_payment_intent_id);
CREATE INDEX idx_payments_status ON payments(status);

-- =====================================================
-- ADMIN REPORTS TABLE
-- =====================================================
CREATE TABLE admin_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type TEXT NOT NULL CHECK (type IN ('daily', 'weekly', 'monthly', 'custom')),
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  
  -- Report content (generated by Claude)
  content JSONB NOT NULL,
  summary TEXT NOT NULL,
  
  -- AI generation tracking
  generated_by TEXT NOT NULL DEFAULT 'claude-3.5-sonnet',
  tokens_used INTEGER NOT NULL,
  cost_gbp DECIMAL(10,6) NOT NULL,
  
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_reports_type ON admin_reports(type);
CREATE INDEX idx_reports_period ON admin_reports(period_start DESC, period_end DESC);

-- =====================================================
-- AI COSTS TABLE (Real-time tracking)
-- =====================================================
CREATE TABLE ai_costs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Operation details
  operation TEXT NOT NULL, -- 'pricing', 'annotation', 'training', 'report_generation'
  provider TEXT NOT NULL CHECK (provider IN ('openai', 'anthropic')),
  model TEXT NOT NULL, -- 'gpt-4o', 'claude-3.5-sonnet'
  
  -- Token usage
  tokens_input INTEGER NOT NULL,
  tokens_output INTEGER NOT NULL,
  tokens_cached INTEGER NOT NULL DEFAULT 0,
  
  -- Cost calculation
  cost_gbp DECIMAL(10,6) NOT NULL,
  
  -- Context
  task_id UUID REFERENCES tasks(id) ON DELETE SET NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for analytics
CREATE INDEX idx_ai_costs_operation ON ai_costs(operation);
CREATE INDEX idx_ai_costs_provider ON ai_costs(provider);
CREATE INDEX idx_ai_costs_timestamp ON ai_costs(timestamp DESC);
CREATE INDEX idx_ai_costs_task_id ON ai_costs(task_id);

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE annotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_costs ENABLE ROW LEVEL SECURITY;

-- Users policies
CREATE POLICY "Users can view own profile"
  ON users FOR SELECT
  USING (auth.uid()::text = clerk_id);

CREATE POLICY "Users can update own profile"
  ON users FOR UPDATE
  USING (auth.uid()::text = clerk_id);

-- Tasks policies
CREATE POLICY "Users can view own tasks"
  ON tasks FOR SELECT
  USING (user_id IN (SELECT id FROM users WHERE clerk_id = auth.uid()::text));

CREATE POLICY "Admins can view all tasks"
  ON tasks FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE clerk_id = auth.uid()::text AND role = 'admin'
  ));

CREATE POLICY "Users can create own tasks"
  ON tasks FOR INSERT
  WITH CHECK (user_id IN (SELECT id FROM users WHERE clerk_id = auth.uid()::text));

-- Annotations policies
CREATE POLICY "Users can view annotations for own tasks"
  ON annotations FOR SELECT
  USING (task_id IN (
    SELECT id FROM tasks 
    WHERE user_id IN (SELECT id FROM users WHERE clerk_id = auth.uid()::text)
  ));

CREATE POLICY "Admins can view all annotations"
  ON annotations FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE clerk_id = auth.uid()::text AND role = 'admin'
  ));

-- Payments policies
CREATE POLICY "Users can view own payments"
  ON payments FOR SELECT
  USING (user_id IN (SELECT id FROM users WHERE clerk_id = auth.uid()::text));

CREATE POLICY "Admins can view all payments"
  ON payments FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE clerk_id = auth.uid()::text AND role = 'admin'
  ));

-- Admin reports policies (admin only)
CREATE POLICY "Admins can view all reports"
  ON admin_reports FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE clerk_id = auth.uid()::text AND role = 'admin'
  ));

-- AI costs policies (admin only)
CREATE POLICY "Admins can view all AI costs"
  ON ai_costs FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE clerk_id = auth.uid()::text AND role = 'admin'
  ));

-- =====================================================
-- FUNCTIONS & TRIGGERS
-- =====================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_annotations_updated_at BEFORE UPDATE ON annotations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_payments_updated_at BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Auto-update task metrics when annotations change
CREATE OR REPLACE FUNCTION update_task_metrics()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE tasks
  SET 
    auto_approved_count = (
      SELECT COUNT(*) FROM annotations 
      WHERE task_id = NEW.task_id AND decision_type = 'auto_approved'
    ),
    manual_review_count = (
      SELECT COUNT(*) FROM annotations 
      WHERE task_id = NEW.task_id AND decision_type IN ('ai_assisted', 'manual_review')
    )
  WHERE id = NEW.task_id;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_task_metrics_trigger 
AFTER INSERT OR UPDATE ON annotations
FOR EACH ROW EXECUTE FUNCTION update_task_metrics();

-- =====================================================
-- INITIAL SEED DATA (for testing)
-- =====================================================

-- Create a test admin user (replace with your Clerk user ID after first login)
-- INSERT INTO users (clerk_id, email, role) 
-- VALUES ('user_XXXXXXXXX', 'admin@annotatai.com', 'admin');

-- Note: This will be populated automatically via Clerk webhooks in production
